# src/app/api/schemas.py
"""
Pydantic models for API request/response validation.
"""

from typing import Optional
from pydantic import BaseModel


class Question(BaseModel):
    message: str
    thread_id: Optional[str] = None  # Session ID for conversation memory (generated by frontend)
