# src/app/retrieval/retriever.py
"""
Retriever module for semantic search from Qdrant.
Uses SelfQueryRetriever as primary method.
Returns dict with docs (List[Document]), generated_query, and generated_filter.
Supports optional manual filters as fallback.
"""

from typing import Dict, List, Optional, Any
from langchain.retrievers.self_query.base import SelfQueryRetriever
from langchain_core.documents import Document
from qdrant_client.http.models import FieldCondition, MatchValue

from app.utils.settings import llm, device
from app.ingest.qdrant_factory import QdrantFactory
from app.retrieval.self_query import metadata_field_info, document_content_description


def build_self_query_retriever(k: int = 5) -> SelfQueryRetriever:
    """
    Builds SelfQueryRetriever using QdrantFactory.
    LLM parses query to generate semantic search + metadata filters automatically.
    """
    factory = QdrantFactory(device=device)  # change to "cuda" if GPU available
    vector_store = factory.get_qdrant_vector_store()

    retriever = SelfQueryRetriever.from_llm(
        llm=llm,
        vectorstore=vector_store,
        document_contents=document_content_description,
        metadata_field_info=metadata_field_info,
        enable_limit=True,
        search_kwargs={"k": k},
        verbose=True,  # shows parsed query/filter in console for debug
    )
    return retriever


def retrieve(
    query: str,
    k: int = 5,
    filters: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    """
    Main retrieval function.
    - If no manual filters: uses SelfQueryRetriever (LLM infers filters)
    - If manual filters provided: falls back to basic similarity search
    Returns dict similar to Caio's retrieve node:
      - "docs": List[Document]
      - "generated_query": semantic query generated by LLM (or original query if basic mode)
      - "generated_filter": formatted filter string (or manual filter description)
    """
    factory = QdrantFactory(device=device)
    vector_store = factory.get_qdrant_vector_store()

    if filters:
        # Manual filter mode (fallback)
        qdrant_filter = {"must": [
            FieldCondition(key=f"payload.{key}", match=MatchValue(value=value))
            for key, value in filters.items()
        ]}

        docs = vector_store.similarity_search(query=query, k=k, filter=qdrant_filter)

        return {
            "docs": docs,
            "generated_query": query,  # no LLM parsing in manual mode
            "generated_filter": f"Manual filters: {filters}",
        }

    else:
        # SelfQuery mode (default)
        retriever = build_self_query_retriever(k=k)

        # Get the structured query (query + filter) generated by LLM
        structured_query = retriever.query_constructor.invoke({"query": query})

        # Execute retrieval
        docs = retriever.invoke(query)

        # Format filter for display (simple string version)
        filter_str = str(structured_query.filter) if structured_query.filter else "No filter applied"

        return {
            "docs": docs,
            "generated_query": structured_query.query or query,
            "generated_filter": filter_str,
        }


def get_relevant_documents(query: str, k: int = 5) -> List[Document]:
    """
    LangGraph-compatible: returns only List[Document].
    Uses retrieve internally and extracts just the docs.
    """
    result = retrieve(query=query, k=k)
    return result["docs"]