# src/app/graph/chatbot_graph.py
"""
LangGraph RAG pipeline definition.
Defines the graph structure (nodes + edges) and compiles it.

Graph flow:
    ┌──────────────┐
    │ orchestrator  │  Agent 1: classifies query (casual or technical)
    └──────┬───────┘
           │
           ├── needs_retrieval = false
           │   → END (casual_response already in state)
           │
           └── needs_retrieval = true
               │
        ┌──────┴───────┐
        │   retrieve    │  Vector search in Qdrant (not an LLM agent)
        └──────┬───────┘
               │
        ┌──────┴───────┐
        │    answer     │  Agent 2: generates RAG response from retrieved docs
        └──────┬───────┘
               │
              END

Conversation memory:
    The graph uses LangGraph's MemorySaver as a checkpointer to keep
    conversation history between requests. How it works:

    1. Each conversation session has a unique thread_id (UUID generated by the frontend).
    2. The thread_id is stored in the browser URL (?thread=abc-123) so it
       survives page refreshes (F5).
    3. On each request, chatbot_service.py passes the thread_id in the config:
           COMPILED_GRAPH.stream(state, config={"configurable": {"thread_id": "..."}})
    4. MemorySaver stores the full state (including messages) in a Python dict
       in RAM, keyed by thread_id. On the next request with the same thread_id,
       the LLM receives the previous messages via the "messages" field in state.
    5. "Clear conversation" in the frontend calls POST /clear, which deletes
       all checkpoints for that thread_id from memory, then generates a new thread_id.

    Limitations:
        - Memory lives in RAM only — lost when the server process is killed (Ctrl+C).
        - No automatic cleanup — orphaned threads accumulate until restart.
        - For persistent memory across restarts, replace MemorySaver with
          SqliteSaver (file) or PostgresSaver (database).

The compiled graph (COMPILED_GRAPH) is imported by services/chatbot_service.py
which executes it via COMPILED_GRAPH.stream().
"""

from langgraph.graph import StateGraph, END
from langgraph.checkpoint.memory import MemorySaver

from app.graph.state import RAGState
from app.graph.nodes import (
    orchestrator_node,
    retrieve_node,
    answer_node,
    route_after_orchestrator,
)

# In-memory checkpointer — stores conversation history per thread_id.
# Each thread_id gets its own state history, so the LLM can see previous messages.
# Note: memory is lost when the server restarts.
memory = MemorySaver()


def build_chatbot_graph():
    """Builds and compiles the RAG chatbot graph with memory checkpointer."""
    graph = StateGraph(RAGState)

    # Register the 3 nodes
    graph.add_node("orchestrator", orchestrator_node)   # Agent 1: classify
    graph.add_node("retrieve", retrieve_node)           # Vector search (no LLM)
    graph.add_node("answer", answer_node)               # Agent 2: generate answer

    # Entry point: every question starts at the orchestrator
    graph.set_entry_point("orchestrator")

    # Conditional edge: orchestrator decides the next step
    # - "retrieve" if technical (needs documents from Qdrant)
    # - "__end__"  if casual   (orchestrator already has the response)
    graph.add_conditional_edges(
        "orchestrator",
        route_after_orchestrator,
        {
            "retrieve": "retrieve",
            "__end__": END,
        }
    )

    # Linear edges: retrieve always goes to answer, answer always ends
    graph.add_edge("retrieve", "answer")
    graph.add_edge("answer", END)

    return graph.compile(checkpointer=memory)


# Compiled once at import time — reused for every request
COMPILED_GRAPH = build_chatbot_graph()
