# src/app/graph/rag_graph.py
"""
LangGraph RAG pipeline for 3GPP specifications chatbot.
Uses get_relevant_documents for retrieval.

Orchestrator attempts to answer casual/simple questions directly using JSON output.
If technical → sets needs_retrieval=True and empty response.
"""

from typing import Annotated, List, Dict, TypedDict, Generator, Any
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser, JsonOutputParser
from langgraph.graph import StateGraph, END
from langgraph.graph.message import add_messages

from app.retrieval.retriever import get_relevant_documents
from app.config import llm, get_logger, NUMBER_RETRIEVE_CHUNKS

logger = get_logger(__name__)

class RAGState(TypedDict):
    question: str
    context: str
    answer: Generator[str, None, None]
    messages: Annotated[List[Dict], add_messages]
    needs_retrieval: bool
    casual_response: str

def orchestrator_node(state: RAGState) -> Dict[str, Any]:
    """
    Attempts to answer the question directly if it's casual/simple.
    Uses LLM to output JSON with response and needs_retrieval flag.
    """
    logger.info(f"Graph - Orchestrating for: {state['question']}")

    parser = JsonOutputParser()

    classify_prompt = ChatPromptTemplate.from_messages([
        ("system", "You are a friendly 3GPP specs chatbot assistant. "
                   "If the query is casual, simple, or non-technical (e.g., greetings, general chat), "
                   "provide a helpful response and set needs_retrieval to false. "
                   "If it requires technical information from 3GPP specifications, "
                   "do not answer, leave response empty, and set needs_retrieval to true. "
                   "{format_instructions}\n"
                   "Examples:\n"
                   "- Query: 'Oi' -> {{\"response\": \"Oi! Como posso ajudar hoje?\", \"needs_retrieval\": false}}\n"
                   "- Query: 'What is the input for createMOI?' -> {{\"response\": \"\", \"needs_retrieval\": true}}\n"
                   "- Query: 'How are you?' -> {{\"response\": \"I'm good, thanks! Ready to help with 3GPP queries.\", \"needs_retrieval\": false}}\n"
                   "- Query: 'Explain 5G beamforming' -> {{\"response\": \"\", \"needs_retrieval\": true}}"),
        ("human", "Query: {question}"),
    ]).partial(format_instructions=parser.get_format_instructions())

    chain = classify_prompt | llm | parser
    result = chain.invoke({"question": state["question"]})

    needs_retrieval = result.get("needs_retrieval", True)
    casual_response = result.get("response", "")

    logger.info(f"Graph - Needs retrieval: {needs_retrieval}")
    return {"needs_retrieval": needs_retrieval, "casual_response": casual_response}

def casual_generate_node(state: RAGState) -> Dict[str, Any]:
    """
    Streams the response that was already generated by the orchestrator (casual case).
    """
    logger.info("Graph - Streaming casual / direct response...")

    def word_stream():
        # Simple word-by-word streaming to keep UX consistent with technical answers
        for word in state["casual_response"].split():
            yield word + " "

    return {"answer": word_stream()}

def retrieve_node(state: RAGState) -> Dict[str, Any]:
    """
    Retrieves formatted strings using get_relevant_documents.
    """
    logger.info(f"Graph - Retrieving for: {state['question']}")
    formatted_strings = get_relevant_documents(
        query=state["question"],
        k=NUMBER_RETRIEVE_CHUNKS
    )
    context = "\n\n---\n\n".join(formatted_strings)
    logger.info(f"Graph - Retrieved and formatted {len(formatted_strings)} chunks")
    return {"context": context}

def generate_node(state: RAGState) -> Dict[str, Any]:
    """
    Generates streaming response using pre-formatted context.
    """
    logger.info("Graph - Starting generation phase...")
    prompt = ChatPromptTemplate.from_messages([
        ("system", "You are an expert in 3GPP technical specifications. "
                   "Answer the question based only on the provided context. "
                   "Be precise, technical, and concise. "
                   "At the end, list sources in format: "
                   "(Spec: <spec>, Release: <release>, Series: <series>, Chunk Index: <chunk_index>)."),
        ("human", "Question: {question}\n\nContext:\n{context}\n\nAnswer:"),
    ])
    chain = prompt | llm | StrOutputParser()
    answer_stream = chain.stream({
        "question": state["question"],
        "context": state["context"]
    })
    logger.info("Graph - Generation started (streaming tokens)...")
    return {"answer": answer_stream}

def route_after_orchestrator(state: RAGState) -> str:
    """
    Routes to retrieve if technical, or to casual streaming if simple/casual.
    """
    return "retrieve" if state["needs_retrieval"] else "casual_generate"

def build_rag_graph():
    graph = StateGraph(RAGState)

    graph.add_node("orchestrator", orchestrator_node)
    graph.add_node("casual_generate", casual_generate_node)
    graph.add_node("retrieve", retrieve_node)
    graph.add_node("generate", generate_node)

    graph.set_entry_point("orchestrator")

    # Conditional routing after orchestrator
    graph.add_conditional_edges(
        "orchestrator",
        route_after_orchestrator,
        {
            "retrieve": "retrieve",
            "casual_generate": "casual_generate",
        }
    )

    graph.add_edge("retrieve", "generate")
    graph.add_edge("casual_generate", END)
    graph.add_edge("generate", END)

    return graph.compile()

COMPILED_GRAPH = build_rag_graph()

def run_rag(question: str) -> Generator[Dict[str, Any], None, None]:
    logger.info(f"RAG execution started for question: {question}")
    initial_state: RAGState = {"question": question, "messages": []}

    for event in COMPILED_GRAPH.stream(initial_state):
        if "generate" in event:
            answer_stream = event["generate"]["answer"]
            for token in answer_stream:
                yield {"type": "token", "data": token}

        elif "casual_generate" in event:
            answer_stream = event["casual_generate"]["answer"]
            for token in answer_stream:
                yield {"type": "token", "data": token}

        if END in event:
            logger.info("RAG execution completed.")
            yield {"type": "end", "data": None}